include:
  - project: auros/ci-pipeline-includes
    ref: master
    file: Container-Scanning.yml

stages:
  - build
  - audit

variables:
  ENCLAVE_BUILD_IMAGE: registry.gitlab.com/auros/enclave-builder@sha256:5ebd1fe845df7d5751f4c95171002cca37b922dc1cf8add28d5961a8ea471952
  DOCKER_HOST: tcp://docker:2375


default:
  image:
    name: $ENCLAVE_BUILD_IMAGE
    entrypoint: [""]
  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:24-dind
      alias: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  retry: 2


.build and publish:
  stage: build
  script:
  - export CONTAINER_NAME=${PROCESS_NAME}
  - echo ${SSH_PRIVATE_KEY_BASE64} | base64 -d -w 0 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - git clone --depth 1 ${CONFIG_REPO_URI} config
  - export _NORMALISED_NAME=${PROCESS_NAME//-/_}
  - export _NORMALISED_NAME=${_NORMALISED_NAME^^}
  - export _INFERRED_VAULT_APPROLE_ID=VAULT_APPROLE_ID_${_NORMALISED_NAME}
  - export _INFERRED_VAULT_SECRET_ID=VAULT_SECRET_ID_${_NORMALISED_NAME}
  - export _INFERRED_VAULT_WALLET_NAME=VAULT_WALLET_NAME_${_NORMALISED_NAME}
  - export VAULT_APPROLE_ID=${!_INFERRED_VAULT_APPROLE_ID}
  - export VAULT_SECRET_ID=${!_INFERRED_VAULT_SECRET_ID}
  - export VAULT_WALLET_NAME=${!_INFERRED_VAULT_WALLET_NAME}
  - "[[ \"${VAULT_APPROLE_ID}\" ]] || { echo \"VAULT_APPROLE_ID is not defined\"; }"
  - "[[ \"${VAULT_SECRET_ID}\" ]] || { echo \"VAULT_SECRET_ID is not defined\"; }"
  - "[[ \"${VAULT_WALLET_NAME}\" ]] || { echo \"VAULT_WALLET_NAME is not defined\"; }"
  - "[[ -f config/${PROCESS_NAME}.json ]] || { echo \"No config found for ${PROCESS_NAME}\"; }"
  - export CONTEXT_ID=$(jq -r '.enclave.cid | select(. != null)' config/${PROCESS_NAME}.json)
  - rm -rf config
  - ./ImageBuilder.sh --enclave


.enclaves: &enclaves
  - PROCESS_NAME: dex_proxy-dexa-main
    CONFIG_REPO_URI: git@bitbucket.org:kenetic/config-prod.git
  - PROCESS_NAME: dex_proxy-dexa-fuji
    CONFIG_REPO_URI: git@bitbucket.org:kenetic/config-dev.git
  - PROCESS_NAME: dex_proxy-uni3-goerli-4
    CONFIG_REPO_URI: git@bitbucket.org:kenetic/config-dev.git
  - PROCESS_NAME: dex_proxy-chainEth-uni3-main-1
    CONFIG_REPO_URI: git@bitbucket.org:kenetic/config-prod.git
  - PROCESS_NAME: dex_proxy-pdex-main
    CONFIG_REPO_URI: git@bitbucket.org:kenetic/config-prod.git
  - PROCESS_NAME: dex_proxy-pdex-testnet
    CONFIG_REPO_URI: git@bitbucket.org:kenetic/config-dev.git


build:
  extends:
    - .build and publish
  parallel:
    matrix: *enclaves


container_scanning:
  before_script: []
  parallel:
    matrix: *enclaves
  # TODO: this would speed up the pipeline quite a bit, but it is not yet supported.
  # https://gitlab.com/gitlab-org/gitlab/-/issues/396845
  #dependencies:
  #  - "build: [${DOCKERFILE}, ${CONTAINER_ADDITIONAL_TAG}, ${CONTAINER_NAME}]"
  variables:
    CS_IMAGE: ${CI_REGISTRY_IMAGE}/${PROCESS_NAME}:${CI_COMMIT_SHA}
    DTRACK_PROJECT_NAME: ${PROCESS_NAME}
    DTRACK_PROJECT_VERSION: ${CI_COMMIT_SHA}
    DTRACK_PROJECT_PARENT_NAME: dex-proxy
