stages:
  - build


variables:
  ENCLAVE_BUILD_IMAGE: registry.gitlab.com/auros/enclave-builder@sha256:ea8814e4157bed0889ba268c40af1fa2ebdce52d6944433d8e9c0ac093f8aca1
  DOCKER_HOST: tcp://docker:2375


default:
  image:
    name: $ENCLAVE_BUILD_IMAGE
    entrypoint: [""]
  services:
    - docker:20-dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  retry: 2


.default_build_script: &default_build_script
  - export CONTAINER_NAME=${PROCESS_NAME}
  - echo ${SSH_PRIVATE_KEY_BASE64} | base64 -d -w 0 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
  - git clone --depth 1 ${CONFIG_REPO_URI} config
  - "[[ -f config/${PROCESS_NAME}.json ]] || { echo \"No config found for ${PROCESS_NAME}\"; }"
  - export CONTEXT_ID=$(jq -r '.enclave.cid | select(. != null)' config/${PROCESS_NAME}.json)
  - rm -rf config
  - ./ImageBuilder.sh --enclave


build dex_proxy-dexa-main:
  stage: build
  script:
    - export PROCESS_NAME=dex_proxy-dexa-main
    - export VAULT_APPROLE_ID=${VAULT_APPROLE_ID_DEX_PROXY_DEXA_MAIN}
    - export VAULT_SECRET_ID=${VAULT_SECRET_ID_DEX_PROXY_DEXA_MAIN}
    - export VAULT_WALLET_NAME=${VAULT_WALLET_NAME_DEX_PROXY_DEXA_MAIN}
    - export CONFIG_REPO_URI=git@bitbucket.org:kenetic/config-prod.git
    - *default_build_script


build dex_proxy-dexa-fuji:
  stage: build
  script:
    - export PROCESS_NAME=dex_proxy-dexa-fuji
    - export VAULT_APPROLE_ID=${VAULT_APPROLE_ID_DEX_PROXY_DEXA_FUJI}
    - export VAULT_SECRET_ID=${VAULT_SECRET_ID_DEX_PROXY_DEXA_FUJI}
    - export VAULT_WALLET_NAME=${VAULT_WALLET_NAME_DEX_PROXY_DEXA_FUJI}
    - export CONFIG_REPO_URI=git@bitbucket.org:kenetic/config-dev.git
    - *default_build_script


build dex_proxy-uni3-goerli-4:
  stage: build
  script:
    - export PROCESS_NAME=dex_proxy-uni3-goerli-4
    - export VAULT_APPROLE_ID=${VAULT_APPROLE_ID_DEX_PROXY_UNI3_GOERLI_4}
    - export VAULT_SECRET_ID=${VAULT_SECRET_ID_DEX_PROXY_UNI3_GOERLI_4}
    - export VAULT_WALLET_NAME=${VAULT_WALLET_NAME_DEX_PROXY_UNI3_GOERLI_4}
    - export CONFIG_REPO_URI=git@bitbucket.org:kenetic/config-dev.git
    - *default_build_script


build dex_proxy-chainEth-uni3-main-1:
  stage: build
  script:
    - export PROCESS_NAME=dex_proxy-chainEth-uni3-main-1
    - export VAULT_APPROLE_ID=${VAULT_APPROLE_ID_DEX_PROXY_CHAINETH_UNI3_MAIN_1}
    - export VAULT_SECRET_ID=${VAULT_SECRET_ID_DEX_PROXY_CHAINETH_UNI3_MAIN_1}
    - export VAULT_WALLET_NAME=${VAULT_WALLET_NAME_DEX_PROXY_CHAINETH_UNI3_MAIN_1}
    - export CONFIG_REPO_URI=git@bitbucket.org:kenetic/config-prod.git
    - *default_build_script
