image:
  name: docker:dind

clone:
  depth: 1

definitions:
  services:
    docker:
      memory: 3000

pipelines:
  branches:
    master:
      - step:
          name: Null pipeline
          script:
            - echo "This pipeline is a placeholder"
            - echo "Bitbucket strips signatures on PR merge, so signature verification cannot occur on this branch."
    '**':
      - step:
          name: Verify commit signatures
          services:
            - docker
          image: alpine:3
          script:
            - apk add --no-cache aws-cli git gpg dirmngr gpg-agent bash
            - ./AuthenticateSignedCommits.sh
  tags:
    '**':
      - step:
          name: Verify commit signatures
          services:
            - docker
          image: alpine:3
          script:
            - apk add --no-cache aws-cli git gpg dirmngr gpg-agent bash
            - ./AuthenticateSignedCommits.sh
